### ISSUE TITLE
Ethereum wallet (Chrome extension) - remaining part

### ISSUE THREAD

**Issue by talegift** [talegift/gitcoin#4]
## Overview

This issue is a continuation of #3.

Milestones defined here will be paid directly to the contractor without Gitcoin.

### 2. Asset loading

Bounty: 1,000 DAI

- Loading of asset balances (erc20 tokens & eth)
- Token search field
- Total wallet balance calculation

### 3. Asset sending & transaction history

Bounty: 1,500 DAI

- Sending of ETH
- Sending of erc20 token (calling `.transfer` function)
- Gas price loading, gas cost estimation, tracking account nonce
- Transaction history

### 4. Account management

Bounty: 1,000 DAI

- Account search field
- Add new account screen
- Edit account name
- Delete account
- Add/delete/edit contact address
- Export private key

### 5. Network management

Bounty: 1,000 DAI

- Search field
- Add, delete, edit network
- Network (RPC params) switching - BSC, Ethereum, custom, etc

### 6. Improving send transaction UI

Bounty: 2,000 DAI

- Show most common recipients on asset sending screen
- Recipient search field
- Tx confirmation time slider
- Tx fee estimation in USD
- Show function name of called contract
- Allow input (params of the called smart contract function) editing on tx screen

### 7. Swap

Bounty: 2,000 DAI

- Simple screen with a selection of `from`, `to` assets and amounts and slippage tolerance
- Should use 0x API

After applying to this bounty, DM me on Twitter so we can coordinate https://twitter.com/0xdev0

**Comment by unstylo** [comment]
Hey. I've completed #3 above i.e. `Asset sending & transaction history`. I'll work later on storing transactions initiated by the injected web3 script, after I complete the tx confirm screen as explained [here](https://photos.app.goo.gl/MjNQcX721yjEu4Xj6).

**Comment by unstylo** [comment]
Completed \\\4 ([Accounts Management UX](https://photos.app.goo.gl/TXKd4f8pmj3GD74P7)).
